---
- name: "Test play"
  hosts: core01
  connection: network_cli

  tasks:
#    - name: "get facts"
#      ios_facts:
#        gather_subset: all

    - name: "Command output"
      cli_command:
        command: "show run | sec nat pool"
      register: out
    - name: "Print without regex"
      debug:
        msg: "{{out.stdout}}"
    - name: "Print with regex"
      debug:
        msg: "{{out.stdout | regex_findall('.*pool (.*)_pub_ip (\\S+).*',multiline=True)}}"
    - name: "set_Fact"
      set_fact:
        cust: "{{out.stdout_lines[0] | regex_findall('.*pool (.*)_pub_ip.*')}}"
        ip: "{{out.stdout_lines[0] | regex_findall('.*(\\S+) prefix-length.*')}}"
    - name: "Print var"
      debug:
        msg: "{{ip}}"

    - name: "add line"
      lineinfile:
        path: dump.txt
        line: "{{out.stdout | regex_findall('.*pool (.*)_pub_ip (\\S+).*',multiline=True)}}"
        create: yes
