---
- name: "Test play"
  hosts: core01
  connection: network_cli

  tasks:
#    - name: "get facts"
#      ios_facts:
#        gather_subset: all

    - name: "Command output"
      cli_command:
        command: "show run | sec nat pool"
      register: out
    - name: "Print without regex"
      debug:
        msg: "{{out.stdout}}"
    - name: "Print with regex"
      debug:
        msg: "{{out.stdout | regex_findall('.*pool (.*)_pub_ip (\\S+).*',multiline=True)}}"
    - name: "set_Fact"
      set_fact:
        cust: "{{out.stdout | regex_findall('.*pool (.*)_pub_ip.*') | list}}"
        ip: "{{out.stdout | regex_findall('.* (\\d+.\\d+.\\d+.\\d+) prefix-length.*') | list}}"

    - name: "Print test"
      debug:
        msg: "{{ip}}"

    - name: "Creating list of dict"
      set_fact:
        test: "{{test|default([]) + [{'cust': item.0, 'ip': item.1}] }}"
      with_together:
        - "{{out.stdout | regex_findall('.*pool (.*)_pub_ip.*') | list}}"
        - "{{out.stdout | regex_findall('.* (\\d+.\\d+.\\d+.\\d+) prefix-length.*') | list}}"

    - name: "Print var"
      debug: var=test

    - name: "add line"
      lineinfile:
        path: dump.txt
        line: "result : {{test}}"
        create: yes
