---
- name: "Create Config Directory"
  file:
    path: deploy/files/{{inventory_hostname}}
    state: directory
#  run_once: yes

- name: "Create tmp directory"
  file:
    path: deploy/files/{{inventory_hostname}}/tmp
    state: directory
#  run_once: yes

- name: "Create final config directory"
  file:
    path: deploy/files/{{inventory_hostname}}/final
    state: directory
#  run_once: yes

- name: "Create core config directory"
  file:
    path: deploy/files/core/
    state: directory
  run_once: yes