---
- name: "Load jinja2 template"
  template:
    src: ../templates/prep_fw_route_conf.j2
    dest: ../files/core/fw_route.conf

- name: "Add route commands"
  command:
    cmd: ../files/core/fw_route.conf