---
- name: "Load jinja2 template"
  template:
    src: ../templates/prep_fw_route_conf.j2
    dest: deploy/files/core/fw_route.conf
  delegate_to: localhost

- name: "Add route commands"
  command:
    cmd: deploy/files/core/fw_route.conf
