---
- name: "Command output"
  cli_command:
    command: "show run | sec nat pool"
  register: out
  tags: test

- name: "Create vars file for Public IP"
  set_fact:
    dictlist: "{{dictlist|default([]) + [{'cust': item.0, 'ip': item.1}] }}"
  with_together:
    - "{{out.stdout | regex_findall('.*pool (.*)_pub_ip.*') | list}}"
    - "{{out.stdout | regex_findall('.* (\\d+.\\d+.\\d+.\\d+) prefix-length.*') | list}}"
  tags: test

- name: "Set name to var data"
  set_fact:
    var1 : "temp: {{dictlist}}"
  tags: test

- name: "Save variable to file"
  copy:
    content: "{{var1}}"
    dest: deploy/vars/ext_dictvars.yml
  tags: test