---
ansible_host: 192.168.1.5

vlan:
  - id: 11
    name: cust1
  - id: 22
    name: cust2

interfaces:
  - name: f1/0
    mode: trunk
  - name: f1/1
    mode: trunk
  - name: f1/2
    mode: access
    vlan: 11
  - name: f1/3
    mode: access
    vlan: 11
  - name: f1/4
    mode: access
    vlan: 22
  - name: f1/5
    mode: access
    vlan: 22
